import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const images = [
    { url: "/images/2308_16_SUZIE_FRASER-2.jpg" },
    { url: "/images/2308_16_SUZIE_FRASER-3.jpg" },
    { url: "/images/2308_16_SUZIE_FRASER-5.jpg" },
    { url: "/images/2308_16_SUZIE_FRASER-10.jpg" },
    { url: "/images/2308_16_SUZIE_FRASER-12.jpg" },
  ];

  const [currentIndex, setCurrentIndex] = useState(0);

  const handleImageClick = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % images.length);
  };

  const formatNumber = (number) => {
    return number.toString().padStart(2, '0');
  };

  return (
    <>
      <Head>
        <title>“TRACED WORK”</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="gallery">
          <div className="intro"><h1>“TRACED WORK”</h1> is an intermittent and itinerant museum telling stories from historians, communities, experts, artists, and a cosmic expanse of non-human knowledge holders.</div>
          <div className="images" onClick={handleImageClick}>
            {images.map((image, i) => (
              <figure
                key={i}
                className={i === currentIndex ? "visible" : "hidden"}
              >
                <img src={image.url} alt={`Image ${i + 1}`} />
              </figure>
            ))}
          </div>
          <div className="images_count">
            <span>{formatNumber(currentIndex + 1)}</span>
            <span>of</span>
            <span>{formatNumber(images.length)}</span>
          </div>
        </div>
        <div className="text">
          <div>
            <h2>Shared ritual</h2>
            <p>“Traced Work” is a museum established in 2023. This project invites you into experiences, stories and rituals through proximity (both digital and physical) to the objects that collectively tell our histories. These includes my histories, belonging to the person writing this text, and your histories, the person reading it – as well as those of everyone else who participates in making the museum what it is. The objects in the museum include art works and historic artefacts, as well as books, sounds and spaces. Objects in the broadest sense.</p>
            <p>You are invited to co-write the histories told through “Traced Work” by contributing your own object to the collection without it ever leaving your side.</p>
            <p>The “Traced Work” digital archive acts as a platform for the stories of our objects to be held and shared – and to be recorded in history. In addition to the online archive, an ongoing series of itinerant physical exhibitions, tours and events – called experiences – encourage bodily closeness outside our heavily digitalised lives.</p>

            <h2>Prioritising context</h2>
            <p>“Traced Work” prioritises the contexts in which objects exist and the stories that connect one object to another. Every object in our world has a physical and cultural context – these contexts help us to learn from and about these objects.</p>
            <p>In the “Traced Work” archive, records of each object will include:</p>
            <ul>
              <li>i) a detail photograph, and</li> 
              <li>ii) a context photograph </li>
            </ul>
            <p>(measuring approx. 1m2 of space)</p>
            <p>These two images are intended to together trace an outline of the object in its context. For non-visual objects in the archive, the detail and context photographs can show other representations of form and position, including sound waves, some sense of space-time positioning, and photos of spaces in which the objects were made. </p>
          </div>
          <div></div>
          <div></div>
        </div>
      </main>
      <footer>
        <div>6 (objects)</div>
        <div>12 (connections)</div>
      </footer>
    </>
  );
}
