import Head from "next/head";
import { useState } from "react";
import Link from "next/link";

export default function Home() {
  const images = [
    { url: "/images/2308_16_SUZIE_FRASER-10.jpg", caption: "No. 001 “HTC Dream with ritually sealed charging point” (2008)" },
    { url: "/images/2308_16_SUZIE_FRASER-12.jpg", caption: "No. 002 “Mourners in one” (1470)" },
    { url: "/images/2308_16_SUZIE_FRASER-5.jpg", caption: "No. 003.1 “First Tears” (2023)" },
    { url: "/images/2308_16_SUZIE_FRASER-3.jpg", caption: "No. 003.2 “First Tears” (2023)" },
    { url: "/images/2308_16_SUZIE_FRASER-2.jpg", caption: "No. 004 “What death/life might look like” (2023)" },
    { url: "/images/2308_16_SUZIE_FRASER-9.jpg", caption: "No. 005 Print in the room” (1985)" },
  ];

  const [currentIndex, setCurrentIndex] = useState(0);

  const handleImageClick = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % images.length);
  };

  const formatNumber = (number) => {
    return number.toString().padStart(3, '0');
  };

  const handleAboutClick = (e) => {
    e.preventDefault();
    document.getElementById("about-section").scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <Head>
        <title>“TRACED WORK”</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="gallery">
          <div className="intro">
            <a href="#about-section" onClick={handleAboutClick}>About</a>
            <h1>“TRACED WORK”</h1>
            <div className="socials">
              <Link href="">IG</Link>, <Link href="">E</Link>
            </div>
          </div>
          <div className="images" onClick={handleImageClick}>
            {images.map((image, i) => (
              <figure
                key={i}
                className={i === currentIndex ? "visible" : "hidden"}
              >
                <img src={image.url} alt={`Image ${i + 1}`} />
              </figure>
            ))}
          </div>
          <div className="images_count">
            <span>{formatNumber(currentIndex + 1)}</span>
            <span>of</span>
            <span>{formatNumber(images.length)}</span>
          </div>
        </div>
        <div id="about-section" className="text">
          <h2>No. 1<br />“Grief Objects” </h2>
          <p>In early 2023, a group of objects was found by staff of the St Georges Motor Inn in Naarm/Melbourne. They have since been catalogued and restaged in the room they were found in by Traced Work using social media posts by hotel staff at the time of the initial discovery. Interesting, the source of the sound in the room has never been found and has been consistently playing for 12 months. Cataloguers, investigators and hotel staff have all reported feeling changed by the sound after encountering it.</p>
          <p>The art works and artefacts found in the room date from 100,033 BCE to the present day and appear to tell a story of human experiences of grief and our species’ sometimes unhappy relationship with being-mortal.</p>
          <p>Working with historians, quantum physicists and archaeologists, Traced Work has been able to piece together tentative and sometimes inconsistent descriptions of each of the objects and how they relate to each other.</p>
          <p>Current thinking is that the room was briefly triggered as a portal or tunnel in space-time and the objects were either inadvertently or intentionally gathered into proximity through their dynamic material interconnections. In other words, these objects, all from different points in our universe’s space-time, were attracted by a repeating energy pulse which corresponds to a strand of information to which they all belong, trapping the objects in the room when the pulse concluded. The pattern of the pulse, it is hypothesised, may have been similar to that of irregular crying convulsions often expressed by humans when experiencing grief, which has been repeatedly registered in the cosmos in recent decades.</p>
          <br /><p>Tours of Room 1<br />will run daily from 24 to 26 May 2024.</p>
          <div className="footer">
            <p>24.<br />–26 May, 2024<br />St Georges Motor Inn<br/>(Narrm)</p>
            <p>001–005</p>
          </div>
        </div>
      </main>
      <footer>
        <figcaption>{images[currentIndex].caption}</figcaption>
      </footer>
    </>
  );
}
